export const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const BAG_ADD_PRODUCT = 'BAG_ADD_PRODUCT';
export const BAG_ADD_PRODUCT_SUCCESS = 'BAG_ADD_PRODUCT_SUCCESS';
export const BAG_ADD_PRODUCT_FAILED = 'BAG_ADD_PRODUCT_FAILED';

export const BAG_LIST_PRODUCT = 'BAG_LIST_PRODUCT';
export const BAG_LIST_PRODUCT_FAILED = 'BAG_LIST_PRODUCT_FAILED';
export const BAG_LIST_PRODUCT_SUCCESS = 'BAG_LIST_PRODUCT_SUCCESS';

export const BAG_REMOVE_PRODUCT = 'BAG_REMOVE_PRODUCT';
export const BAG_REMOVE_PRODUCT_FAILED = 'BAG_REMOVE_PRODUCT_FAILED';
export const BAG_REMOVE_PRODUCT_SUCCESS = 'BAG_REMOVE_PRODUCT_SUCCESS';
