const actions = {
  FETCH_PRODUCTS_REQUESTED: 'FETCH_PRODUCTS_REQUESTED',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
  ADD_TOBAG: 'ADD_TOBAG',
  REMOVE_TOBAG: 'REMOVE_TOBAG'

}

export { actions }
